frr defaults traditional
hostname hub-pe1
!
interface lo
 ip address 10.0.0.2/32
 ip ospf area 0
!
interface eth1
 description Link to branch-ce1 (CE-PE, eBGP only - not part of provider OSPF core)
 ip address 10.1.1.2/30
!
interface eth2
 description Link to core-p1
 ip address 10.1.2.1/30
 ip ospf network point-to-point
 ip ospf area 0
 link-params
  enable
  max-bw 12500000
  max-rsv-bw 12500000
  unrsv-bw 0 12500000
  unrsv-bw 7 8750000
 exit-link-params
!
router ospf
 ospf router-id 10.0.0.2
 capability opaque
 mpls-te on
 mpls-te router-address 10.0.0.2
 redistribute static
!
ip route 10.0.0.3/32 10.1.1.1
!
mpls ldp
 router-id 10.0.0.2
 !
 address-family ipv4
  discover edge-sr
  !
  interface eth2
  !
 exit-address-family
!
router bgp 65000
 bgp router-id 10.0.0.2
 no bgp ebgp-requires-policy
 neighbor 10.1.1.1 remote-as 65001
 !
 address-family ipv4 unicast
  neighbor 10.1.1.1 activate
  redistribute connected
  redistribute ospf
 exit-address-family
!
line vty
!