config setup
    charondebug="ike 2, knl 2, cfg 2"

conn hub-to-branch
    authby=secret
    auto=route
    keyexchange=ikev2
    left=10.1.1.2
    leftsubnet=10.0.0.0/24       # The Hub protects the rest of the network Loopbacks
    right=10.1.1.1
    rightsubnet=10.0.0.3/32      # Going to the Branch Loopback
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    dpddelay=10s
    dpdtimeout=30s
    dpdaction=restart