frr defaults traditional
hostname branch-ce1
!
interface lo
 ip address 10.0.0.3/32
 ip ospf area 0
!
interface eth1
 description Link to hub-pe1 (CE-PE, eBGP only - not part of provider OSPF core)
 ip address 10.1.1.1/30
!
router bgp 65001
 bgp router-id 10.0.0.3
 neighbor 10.1.1.2 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.0.0.3/32
  neighbor 10.1.1.2 activate
 exit-address-family
!
line vty
!
