config setup
    charondebug="ike 2, knl 2, cfg 2"

conn branch-to-hub
    authby=secret
    auto=route
    keyexchange=ikev2
    left=10.1.1.1
    leftsubnet=10.0.0.3/32       # ONLY encrypt traffic from the Branch Loopback
    right=10.1.1.2
    rightsubnet=10.0.0.0/24      # ONLY encrypt traffic heading to other Loopbacks
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    dpddelay=10s
    dpdtimeout=30s
    dpdaction=restart