frr defaults traditional
hostname core-p1
!
interface lo
 ip address 10.0.0.1/32
 ip ospf area 0
!
interface eth1
 description Link to hub-pe1
 ip address 10.1.2.2/30
 ip ospf network point-to-point
 ip ospf area 0
 link-params
  enable
  max-bw 12500000
  max-rsv-bw 12500000
  unrsv-bw 0 12500000
  unrsv-bw 7 8750000
 exit-link-params
!
interface eth2
 description Link to dc-1
 ip address 10.1.3.1/30
 ip ospf network point-to-point
 ip ospf area 0
 link-params
  enable
  max-bw 12500000
  max-rsv-bw 12500000
  unrsv-bw 0 12500000
  unrsv-bw 7 8750000
 exit-link-params
!
router ospf
 ospf router-id 10.0.0.1
 capability opaque
 mpls-te on
 mpls-te router-address 10.0.0.1
!
mpls ldp
 router-id 10.0.0.1
 !
 address-family ipv4
  discover edge-sr
  !
  interface eth1
  !
  interface eth2
  !
 exit-address-family
!
line vty
!